services:
  backend:
    image: ghcr.io/rakeshrkb/killer-game-backend:redis-distributed
    container_name: killer-game-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - visitor_data:/app/data
    environment:
      - REDIS_URL=redis:////ip-172-31-10-99.ap-south-1.compute:6379
    env_file:
      - .env

volumes:
  visitor_data:
