services:
  backend:
    image: ghcr.io/rakeshrkb/killer-game-backend:redis-distributed
    container_name: killer-game-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - visitor_data:/app/data
    env_file:
      - .env
  redis:
    image: redis:7-alpine
    container_name: killer-game-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --replicaof ${REDIS_PRIMARY_ADDR} 6379
      --appendonly yes

  sentinel:
    image: redis:7-alpine
    container_name: killer-game-sentinel
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "26379:26379"
    volumes:
      - sentinel_data:/data
    command: >
      sh -c '
      if [ ! -s /data/sentinel.conf ]; then
      printf "port 26379\nsentinel resolve-hostnames yes\nsentinel monitor %s %s 6379 2\nsentinel auth-pass %s %s\nsentinel down-after-milliseconds %s 5000\nsentinel failover-timeout %s 10000\nsentinel parallel-syncs %s 1\n" "$REDIS_MASTER_NAME" "$REDIS_PRIMARY_ADDR" "$REDIS_MASTER_NAME" "$REDIS_PASSWORD" "$REDIS_MASTER_NAME" "$REDIS_MASTER_NAME" "$REDIS_MASTER_NAME" > /data/sentinel.conf;
      fi &&
      redis-server /data/sentinel.conf --sentinel'


volumes:
  visitor_data:
  redis_data:
  sentinel_data:
